### ISSUE TITLE
Failed when compiling grammars in textnorm

### ISSUE THREAD

**Issue by xiaotaw** [saikiranvalluri/sparrowhawk-resources#1]
I have run sparrowhawk's example with en_toy correctly.  And failed when compile grammars in textnorm.
In dir textnorm/classifier, 
`thraxmakedep tokenize_and_classify.grm`
`make -j4`
Here is the err msg:
blabla...
LoadFstFromFar: Unalble to open FAR: universal_depot.far
universal_rules.grm:23:c++ function call failed
complilation failed.
blabla...

**Comment by xiaotaw** [comment]
solved by using create_far.py

**Comment by no-execution** [comment]
> solved by using create_far.py

after running create_far.py

**Comment by no-execution** [comment]
I begin to farcreate and cant find hour module. Do you have this error?
